### PR TITLE
fix(autoware_perception_msgs): add Header to tlr messages and change TrafficLightElement.msg status

### PR DESCRIPTION
**Pull request by Mingyu1991**
This PR contains two modifications:

1. Add header to Traffic Light messages to replace stamps, since it's necessary to use ros2 synchronizer
2. Change values in TrafficLightElement.msg since current traffic light nodes requires the shapes, colors and status have different values.

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by isamu-takagi** [comment]
@Mingyu1991 @yukkysaito 
Is this a temporary change? The message should not change due to implementation.

**Comment by yukkysaito** [comment]
Sorry. I should have checked more closely.
I will talk to mingyu.

**Comment by miursh** [comment]
@isamu-takagi 
@Mingyu1991 says we need header filed in order to use message filter to sync multiple topics. 
Is it possible to change I/F as this PR permanently?

**Comment by isamu-takagi** [comment]
@miursh The way it should be is to modify the message filter. I don't think it's a good choice for interface design. The remaining issue is the trade-off with implementation cost.

**Pull request merged**
