### PR TITLE
feat(autoware_planning_msgs): move header to the top in PoseWithUuidStamped

### PR DESCRIPTION
**Pull request by kosuke55**
## Description

https://github.com/orgs/autowarefoundation/discussions/2983#discussioncomment-4693706

> I added PoseStampedWithUuid in https://github.com/autowarefoundation/autoware_msgs/pull/47
> ```
> geometry_msgs/PoseStamped pose_stamped
> unique_identifier_msgs/UUID uuid
> ```
> 
> and I tried visualizing it with `rviz_common::MessageFilterDisplay`, but it seems to require the `header` at the top of the message
> (https://answers.ros.org/question/307914/problem-with-message_filterscache/)
> 
> so I would like to change the message to
> ```
> std_msgs/Header header
> geometry_msgs/Pose pose
> unique_identifier_msgs/UUID uuid
> ```
> 
> Yes, I would prefer to have the header at the top, given that we can use MessageFilter, and I think it would be easier to understand with the same structure as the other msgs.
> The only drawback is that it requires some conversion, but I don't think it would be a big problem.
> 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Could you also add a README.md file to the `autoware_planning_msgs` top directory and add a small description on what this message will be used for?

**Comment by xmfcx** [comment]
Also you might want to rename the message to `PoseWithUuidStamped`

**Comment by kosuke55** [comment]
thanks, it seems better.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by kosuke55** [comment]
@xmfcx 
Updated the name and description.

**Review by xmfcx — APPROVED** [review]
Thanks for the work!

**Pull request merged**
