### PR TITLE
feat(autoware_perception_msgs): remove traffic light messages

### PR DESCRIPTION
**Pull request by isamu-takagi**
## Description

Remove traffic light messages because they are only used in the perception component.
https://github.com/autowarefoundation/autoware.universe/issues/2567#issuecomment-1611086117

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Mingyu1991** [comment]
I have two concerns:

1. The current traffic_light_multi_camera_fusion package in universe is using the autoware_perception_msgs/TrafficLightElement. Removing the TrafficLightElement.msg would cause build error. What about keeping the old TrafficLightElement.msg and add the new TrafficSignalElement.msg in this PR, replacing the message in traffic_light_mult_camera_fusion in another PR and remove TrafficLightElement.msg in a new PR?
2. The "traffic_signal_id" of TrafficSignal.msg stands for the group id in the lanelet2. Is this name understandable for the users? Could we use other names like regulatory_element_id to distinguish it from the traffic_light_id? Or add some comments in the msg definition?

**Comment by isamu-takagi** [comment]
>The current traffic_light_multi_camera_fusion package in universe is using the autoware_perception_msgs/TrafficLightElement. Removing the TrafficLightElement.msg would cause build error. What about keeping the old TrafficLightElement.msg and add the new TrafficSignalElement.msg in this PR, replacing the message in traffic_light_mult_camera_fusion in another PR and remove TrafficLightElement.msg in a new PR?

The build error is unavoidable as `TrafficSignal.msg` is changed to use `TrafficLSignalElement.msg` instead of `TrafficLightElement.msg`.

>The "traffic_signal_id" of TrafficSignal.msg stands for the group id in the lanelet2. Is this name understandable for the users? Could we use other names like regulatory_element_id to distinguish it from the traffic_light_id? Or add some comments in the msg definition?

The name `regulatory element` depends on lanelet2 format. This message is independent of the map format, so I think it's better not to change the field name or add comments that are format dependent.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by Mingyu1991 — APPROVED** [review]
LGTM

**Pull request merged**
