### PR TITLE
feat(autoware_msgs): add new optional messages package with published time debug message

### PR DESCRIPTION
**Pull request by brkay54**
## Description

Closes: https://github.com/autowarefoundation/autoware.universe/issues/6255

We want to add a new message which will report the header time and published time of a message inside the pipelines.
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by mitsudome-r** [comment]
Let's create a new package called autoware_debug_msgs since this won't be used as a main interface.

**Comment by yukkysaito** [comment]
This is not a formal interface and should not be included in autoware_msgs. :pray:

**Comment by mitsudome-r** [comment]
I have created https://github.com/autowarefoundation/autoware_internal_msgs so let's put this message there.

**Comment by brkay54** [comment]
https://github.com/autowarefoundation/autoware_internal_msgs/pull/1 Created another PR.

**Pull request closed without merging**
