### PR TITLE
feat(autoware_planning_msgs)!: remove PathWithLaneId msgs

### PR DESCRIPTION
**Pull request by mitsudome-r**
## Description

PathWithLaneId is not an official interface for Autoware: https://autowarefoundation.github.io/autoware-documentation/main/design/autoware-interfaces/components/planning/

If this must be added, it should go under autoware_internal_msgs repository.
For now, the message isn't used in the code so there is not issue with removing the message.

## Tests performed
Autoware builds without an error.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Review by esteve — APPROVED** [review]

**Comment by esteve** [comment]
@youtalk I believe I don't have write access to this repo, could you review these changes and approve them? PRs need two approvals from people with write access and @yukkysaito already approved this PR. Thanks.

**Review by youtalk — APPROVED** [review]
LGTM
@esteve Thank you for your mention.

**Comment by youtalk** [comment]
@mitsudome-r I think the current branch protection rule is too strong. We cannot merge any PRs to main. Could you fix it?

https://github.com/autowarefoundation/autoware_msgs/rules/847626?ref=refs%2Fheads%2Fmain

**Comment by xmfcx** [comment]
It says "The base branch does not allow updates." checking again.

**Comment by xmfcx** [comment]
image

What is being merged btw?

**Review by xmfcx — CHANGES_REQUESTED** [review]
this pr changes nothing

**Comment by esteve** [comment]
@xmfcx you're right, looks like this message was already removed https://github.com/autowarefoundation/autoware_msgs/tree/main/autoware_planning_msgs/msg

**Comment by xmfcx** [comment]
Thanks @esteve closing it then.

**Pull request closed without merging**
