### PR TITLE
feat(autoware_map_msgs): migrate autoware_auto_mapping_msgs to autowa…

### PR DESCRIPTION
**Pull request by cyn-liu**
## Description

migrate [autoware_auto_mapping_msgs](https://github.com/tier4/autoware_auto_msgs/tree/tier4/main/autoware_auto_mapping_msgs) to autoware_map_msgs.

migrate three messages:
`HDMapBin.msg`
`MapPrimitive.msg`
`HDMapSegment.msg`

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Could you look into this PR:
- https://github.com/autowarefoundation/autoware_msgs/pull/30

I've added these as:
- https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_map_msgs/msg/LaneletMapBin.msg
- https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletRoute.msg
- https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletSegment.msg
- https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletPrimitive.msg

**Comment by cyn-liu** [comment]
> Could you look into this PR:
> 
> * [feat(map-messages): add LaneletMapBin.msg #30](https://github.com/autowarefoundation/autoware_msgs/pull/30)
> 
> I've added these as:
> 
> * https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_map_msgs/msg/LaneletMapBin.msg
> * https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletRoute.msg
> * https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletSegment.msg
> * https://github.com/autowarefoundation/autoware_msgs/blob/main/autoware_planning_msgs/msg/LaneletPrimitive.msg

Thanks @xmfcx :
Due to my negligence, I did not see the previous PR, I will close this PR.

I see that the `Universe` repository is still using the `autoware_auto_map_msg`, Have you made a PR for modification?

**Comment by xmfcx** [comment]
> Due to my negligence, I did not see the previous PR, I will close this PR.

@cyn-liu It was our fault too, not making these changes obvious. I'm sorry that you've lost time.

> I see that the Universe repository is still using the `autoware_auto_map_msg`, Have you made a PR for modification?

No, we should update the repository to use these new messages. I think you can start working on this task.

For the control messages I have the following issue with 5 related PRs:
- https://github.com/autowarefoundation/autoware.universe/issues/3674

Right now, once the adapter node is created, I will merge rest of them.

Adapter node is to not break compatibility with outside simulator environments.

**Comment by cyn-liu** [comment]
> No, we should update the repository to use these new messages. I think you can start working on this task.
> 
thanks, great job. 
I plan to update  the `Universe` repos with new `autoware_map_msg`.

**Comment by cyn-liu** [comment]
> No, we should update the repository to use these new messages. I think you can start working on this task.
> 
thanks, great job. 
I plan to update  the `Universe` repos with new `autoware_map_msg`.

**Pull request closed without merging**
