### PR TITLE
docs(message-guidelines): link message guidelines

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

I've separated the message guidelines to its own PR.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Following https://github.com/autowarefoundation/autoware_msgs/pull/11#issuecomment-1104077785

@isamu-takagi I've added the enumerations section.

**Comment by xmfcx** [comment]
I've moved it to here for more visibility:

https://github.com/autowarefoundation/autoware-documentation/pull/94

https://autowarefoundation.github.io/autoware-documentation/pr-94/contributing/coding-guidelines/message-guidelines/

And this PR just adds a link to it once that is merged.

**Comment by kenji-miyake** [comment]
Is this `docs`, not `feat`?

**Review by kenji-miyake — APPROVED** [review]
I changed the PR title to `docs`.

**Comment by kenji-miyake** [comment]
Ah, but if auto-merge is set, it seems to be not affected. :disappointed: 
image

**Pull request merged**
