### PR TITLE
refactor(autoware_map_msgs): modify pcd metadata msg

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Description
To match the structure of the Lanelet2 metadata message, I will modify the PointCloud metadata message. https://github.com/autowarefoundation/autoware_msgs/pull/81#discussion_r1665139601

- add cell_id to `PointCloudMapCellMetaData.msg`
- delete `PointCloudMapCellMetaDataWithID.msg`
- rename `PointCloudMapCellMetaDataWithID.msg` to `PointCloudMapCellWithMetaData.msg`

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by yukkysaito — APPROVED** [review]
LGTM

**Comment by xmfcx** [comment]
@youtalk san, since we switched to version based repo tracking, this needs to be released and updated.

- https://github.com/autowarefoundation/autoware/actions/runs/10075917600/job/27855197516?pr=5022#step:5:13903 is failing.

- https://github.com/autowarefoundation/autoware/blob/3e7f3d4af81632107ab7d4c2ba2c32ba786b66ad/autoware.repos#L3-L6

I think we will need to formally do a release for every PR in these repositories with versions, is that alright?

**Comment by youtalk** [comment]
@xmfcx The core packages' version control partially prevents the API breakage which I expected. 
We need to release the package by semantic versioning. 

@YamatoAndo Generally speaking, we should not casually break the API. Please reconsider your changes.

**Comment by xmfcx** [comment]
This was reverted by:
- https://github.com/autowarefoundation/autoware_msgs/pull/98

**Pull request merged**
