### PR TITLE
refactor(planning-messages)!: rename VectorMap to Lanelet

### PR DESCRIPTION
**Pull request by xmfcx**
Signed-off-by: M. Fatih Cırıt <mfc@leodrive.ai>

## Description

Related PR: https://github.com/autowarefoundation/autoware_msgs/pull/30#issuecomment-1306787524

For consistency, this PR renames the `VectorMap` to `HadMap` which stands for **Highly Automated Driving** Map.

@isamu-takagi is this change ok? I wish I've brought it up while reviewing https://github.com/autowarefoundation/autoware_msgs/pull/33 I'm sorry.

Is this message used in the current Autoware Universe?

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@mitsudome-r @kenji-miyake  @yukkysaito 
What do you think about this? I couldn't imagine what kind of map it was compared to point cloud map. If this PR is merged, only renaming is enough, so the impact is small.

**Comment by mitsudome-r** [comment]
I personally don't mind with either name as long as it is consistent between this message and [map message](https://github.com/autowarefoundation/autoware_msgs/pull/30) if they are referring to the same map.

**Comment by xmfcx** [comment]
@isamu-takagi @mitsudome-r if it's ok, can you approve it?

**Comment by kenji-miyake** [comment]
I personally prefer `VectorMap` to `HadMap` because `Highly Automated Driving Map` sounds ambiguous to me. `VectorMap` gives me a clear image that it has vector features.
The word `vector features` is widely used in the GIS field.
https://desktop.arcgis.com/en/arcmap/10.3/manage-data/geodatabases/feature-class-basics.htm

@xmfcx What makes you feel `HadMap` is better? If you have strong opinions, I think it's okay to merge this PR. But I'd like to make the reasons clear for future discussions.

**Comment by yukkysaito** [comment]
I prefer VectorMap. Because it is paired with PointCloudMap.
I don't have a strong preference but would like to unify one or the other. :+1:

**Comment by xmfcx** [comment]
Truth is, I also don't have a strong opinion. But I also want it to be correct.

Some references using the word HAD:
- https://store.frost.com/high-definition-maps-for-automated-driving.html
- http://www.mrt.kit.edu/z/publ/download/2018/Poggenhans2018Lanelet2.pdf
  - > The term ”high-definition” (HD) map is often misleadingly used for the latter two, but it is not precisely defined.
In this paper we therefore use the term lane-level accurate map for the first, while maps that enable safe highly automated driving (HAD) even in complex city center scenarios will be referred to as HAD maps.

The second paper is the reason I was convinced to use the term HAD map.

@yukkysaito @kenji-miyake what about using `LaneletMapPrimitive`, `LaneletMapSegment`, `LaneletMapRoute`, `LaneletMapBin`

The reason I don't like term `Vector map` is that it's too general https://en.wikipedia.org/wiki/Vector_Map

But I will be fine either way, as long as we decide on something.

**Comment by xmfcx** [comment]
Even `LaneletPrimitive`, `LaneletSegment`, `LaneletRoute`, `LaneletMap` (following the naming in https://github.com/fzi-forschungszentrum-informatik/Lanelet2/blob/master/lanelet2_core/doc/Architecture.md#overview-and-interaction ) can be a good way of doing it.

**Comment by isamu-takagi** [comment]
I think `LaneletRoute, etc.` are a good if the map format is lanelet only, otherwise, a more general name such as `VectorMapRoute` would be better. So how about renaming it to `Lanalet` for now and discussing it again when other formats are needed?

**Comment by xmfcx** [comment]
> I think `LaneletRoute`, etc. are a good if the map format is lanelet only, otherwise, a more general name such as `VectorMapRoute` would be better.

We right now don't know if we can even process other kinds of vector maps in the same way as lanelet2 like with primitives, segments. So I'd suggest we only process lanelet2 format in Autoware. And any other format should be converted to lanelet2 we want to use it with the Autoware.

> So how about renaming it to `Lanelet` for now and discussing it again when other formats are needed?

I'm ok with this. @yukkysaito @kenji-miyake @isamu-takagi @mitsudome-r any opinions?

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Review by isamu-takagi — APPROVED** [review]

**Pull request merged**
